"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Street View Upload Tool.py']
DATA_FILES = ['streetviewpublish_config.json']
OPTIONS = {'packages': ['httplib2','requests','oauth2client','apiclient'], 'iconfile':'sv_uploader.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
