"""
This is a setup.py script generated by py2applet

Usage:
    python setup2.py py2app
"""

from setuptools import setup

APP = ['Street View Timelapse Uploader.py']
DATA_FILES = ['streetviewpublish_config.json']
OPTIONS = {'argv_emulation': True, 'includes':['exiftool','ffmpeg','pycurl'], 'packages':['httplib2','requests','oauth2client','apiclient'], 'iconfile':'sv_uploader.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
)
